### ISSUE TITLE
new option: azimut

### ISSUE THREAD

**Issue by Olegga666** [NLTGit/Leaflet.LinearMeasurement#1]
Hello. Good plugin. Can you add option 'azimut' like this: [https://drive.google.com/open?id=0B-p7Lmut51g6M1ZvRnBGd2dUNWc](https://drive.google.com/open?id=0B-p7Lmut51g6M1ZvRnBGd2dUNWc)

**Comment by longenecker79** [comment]
Greetings Olegga,
 
It's definitely doable.  My colleagues and I are going to review this request and get back to you.
 
Regards,
--------------------------------------------------------------------------------------------------------------
Jason Longenecker
PMP, PHR, SPHR, LSS GB & ITIL v4 
New Light Technologies, Inc.
1100 H Street, NW Suite 700
Washington, DC 20005
Phone: 202-568-6300 Ext. 9004
Fax: 202-568-6301
[  ]( http://www.newlighttechnologies.com/ )
[ http://www.NewLightTechnologies.com ]( http://www.NewLightTechnologies.com )[  ]( http://www.NewLightTechnologies.com )
[ http://Utility-LINE.com ]( http://utility-line.com )
[ http://www.linkedin.com/in/NewLighTtechnologies ]( http://www.linkedin.com/in/NewLighTtechnologies )[  ]( http://www.linkedin.com/in/NewLighTtechnologies )
[ http://twitter.com/#!/NLTMarketing ]( http://twitter.com/#!/NLTMarketing )[  ]( http://twitter.com/#!/NLTMarketing )
[ https://www.linkedin.com/in/LongeneckerJason ]( https://www.linkedin.com/in/longeneckerjason ) 
[ https://plus.google.com/+JasonLongeneckerDC ]( https://plus.google.com/+JasonLongeneckerDC )
 
This email transmission, and any attachments to it, contain privileged information of New Light Technologies, Inc. (NLT) and may not be disclosed, used, copied, or transmitted in any form or by any means without prior written permission from NLT. If you are not the intended recipient, delete the transmission and any attachments from your system and kindly notify the sender by email. Thank you. 
 
P Please consider the environment before printing this email. 


-----Original Message-----

**Comment by juandfloresm** [comment]
Hi,

There is a new branch called **issue-1-azimut**. Please feel free to try this change there.
We will discuss this change in order to be sure we are merging it.

Thanks

**Comment by juandfloresm** [comment]
New option would be **show_azimut** for consistency with other requests.

**Comment by longenecker79** [comment]
Nice Juan!
Is there a link I can demo this from.


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by juandfloresm** [comment]
Sorry not at this moment. But will be part of the demo once in the trunk. Please take a look at the following image:

<img width="650" alt="screen shot 2017-03-20 at 7 08 38 am" src="https://cloud.githubusercontent.com/assets/1584979/24113133/c7c99592-0d69-11e7-8a6d-1706a6c98e45.png">

**Comment by juandfloresm** [comment]
This feature has been merged

**Comment by Olegga666** [comment]
Thank you, еhis is what was needed.
