### ISSUE TITLE
last point

### ISSUE THREAD

**Issue by prancius** [NLTGit/Leaflet.LinearMeasurement#3]
When user clicks twice you showing a label with total, but removing little circle at the line end, would be nice if poly-line will end with point (little circle)

**Comment by juandfloresm** [comment]
We are using a polyline to depict measurement segments. The last node was removed because it looks cluttered with the label sometimes.

See a new change that allows to customize this behaviour with a boolean option **show_last_node** true/false. Default will be false for the reason explained.
