### ISSUE TITLE
bad calcutalion when last node true

### ISSUE THREAD

**Issue by prancius** [NLTGit/Leaflet.LinearMeasurement#5]
can you check why when show_last_node is enabled total value of this node calculated wrong. Point value and label values should be the same or do not need to show last point title.
[http://infoside.lt/failai/leaflet/error1.png](http://infoside.lt/failai/leaflet/error1.png)

**Comment by juandfloresm** [comment]
Interesting. We can't reproduce the big discrepancies presented in your image. Yet we have modified the approach of having a last node. Please take a look at **issue-5-hotfix** branch. We'll be discussing a merge very soon. Thanks!
